<?php

// Default illustrations only. Uploaded menu images always take precedence.
return [
    'tubruk' => ['sheet' => 'set-01.png', 'column' => 0, 'row' => 0],
    'espresso' => ['sheet' => 'set-01.png', 'column' => 1, 'row' => 0],
    'lungo' => ['sheet' => 'set-01.png', 'column' => 2, 'row' => 0],
    'ristretto' => ['sheet' => 'set-01.png', 'column' => 0, 'row' => 1],
    'americano' => ['sheet' => 'set-01.png', 'column' => 1, 'row' => 1],
    'limericano' => ['sheet' => 'set-01.png', 'column' => 2, 'row' => 1],
    'long-black' => ['sheet' => 'set-02.png', 'column' => 0, 'row' => 0],
    'americano-premium-beans' => ['sheet' => 'set-02.png', 'column' => 1, 'row' => 0],
    'magic-latte' => ['sheet' => 'set-02.png', 'column' => 2, 'row' => 0],
    'dirty-latte' => ['sheet' => 'set-02.png', 'column' => 0, 'row' => 1],
    'cafe-latte' => ['sheet' => 'set-02.png', 'column' => 1, 'row' => 1],
    'cappuccino' => ['sheet' => 'set-02.png', 'column' => 2, 'row' => 1],
    'aren-latte' => ['sheet' => 'set-03.png', 'cell_height' => 4, 'column' => 0, 'row' => 0],
    'spanish-latte' => ['sheet' => 'set-03.png', 'cell_height' => 4, 'column' => 1, 'row' => 0],
    'hazelnut-latte' => ['sheet' => 'set-03.png', 'cell_height' => 4, 'column' => 2, 'row' => 0],
    'caramel-latte' => ['sheet' => 'set-03.png', 'cell_height' => 4, 'column' => 0, 'row' => 1],
    'vanilla-latte' => ['sheet' => 'set-03.png', 'cell_height' => 4, 'column' => 1, 'row' => 1],
    'sea-salt-latte' => ['sheet' => 'set-03.png', 'cell_height' => 4, 'column' => 2, 'row' => 1],
    'butterscotch-latte' => ['sheet' => 'set-04.png', 'column' => 0, 'row' => 0],
    'caramel-macchiato' => ['sheet' => 'set-04.png', 'column' => 1, 'row' => 0],
    'butterscotch-caramel' => ['sheet' => 'set-04.png', 'column' => 2, 'row' => 0],
    'offroad-creamy-latte' => ['sheet' => 'set-04.png', 'column' => 0, 'row' => 1],
    'matcha' => ['sheet' => 'set-04.png', 'column' => 1, 'row' => 1],
    'signature-chocolate' => ['sheet' => 'set-04.png', 'column' => 2, 'row' => 1],
    'taro-latte' => ['sheet' => 'set-05.png', 'column' => 0, 'row' => 0],
    'red-velvet-latte' => ['sheet' => 'set-05.png', 'column' => 1, 'row' => 0],
    'signature-tea' => ['sheet' => 'set-05.png', 'column' => 2, 'row' => 0],
    'tea-telang' => ['sheet' => 'set-05.png', 'column' => 0, 'row' => 1],
    'vanilla-tea' => ['sheet' => 'set-05.png', 'column' => 1, 'row' => 1],
    'lychee-tea' => ['sheet' => 'set-05.png', 'column' => 2, 'row' => 1],
    'lemon-tea' => ['sheet' => 'set-06.png', 'column' => 0, 'row' => 0],
    'milk-tea' => ['sheet' => 'set-06.png', 'column' => 1, 'row' => 0],
    'nasi-ayam-betutu' => ['sheet' => 'set-06.png', 'column' => 2, 'row' => 0],
    'indomie' => ['sheet' => 'set-06.png', 'column' => 0, 'row' => 1],
    'indomie-telur' => ['sheet' => 'set-06.png', 'column' => 1, 'row' => 1],
    'roti' => ['sheet' => 'set-06.png', 'column' => 2, 'row' => 1],
    'dimsum' => ['sheet' => 'set-07.png', 'column' => 0, 'row' => 0],
    'roti-bakar' => ['sheet' => 'set-07.png', 'column' => 1, 'row' => 0],
    'kentang-goreng' => ['sheet' => 'set-07.png', 'column' => 2, 'row' => 0],
    'nugget' => ['sheet' => 'set-07.png', 'column' => 0, 'row' => 1],
    'affogato' => ['sheet' => 'set-07.png', 'column' => 1, 'row' => 1],
    'extra-ice-cream' => ['sheet' => 'set-07.png', 'column' => 2, 'row' => 1],
];
